name: pub_crawl
description: Crawls, fetches and queries published pub packages.
version: 0.1.0
homepage: https://github.com/pq/pub_crawl

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  cli_util: ^0.3.0
  linter: ^1.0.0
  pool: ^1.4.0
  yaml: ^3.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.16.0

# Update to point to your local linter source for lint rule testing.
#dependency_overrides:
#  linter:
#    path:
#      ../linter
