name: pub_crawl
description: Crawls, fetches and queries published pub packages.
version: 0.1.0
homepage: https://github.com/pq/pub_crawl

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  analyzer: ^3.0.0
  args: ^2.0.0
  cli_util: ^0.3.0
  collection: ^1.15.0
  http: ^0.13.4
  linter: ^1.0.0
  meta: ^1.7.0
  path: ^1.8.1
  pub_semver: ^2.1.0
  pool: ^1.4.0
  yaml: ^3.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

# Update to point to your local linter source for lint rule testing.
#dependency_overrides:
#  linter:
#    path:
#      ../linter
