name: pub_crawl
description:
version: 0.0.1
homepage: https://github.com/pq/pub_crawl

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  cli_util: ^0.1.3

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
